In [1]:
import pandas as pd

In [2]:
from pandas import Series, DataFrame

In [3]:
#Series
obj = pd.Series([4, 7, -5,3])

In [4]:
obj #由于未指定索引，于是会自动创建一个0到N-1（N为数据的长度）的整数型索引

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values #获取值

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index #获取索引

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4, 7, -5,3],index =['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
#通过索引的方式选取Series中的单个或一组值
obj2['a']

-5

In [12]:
obj2[['d','a','c']] #索引一组值时需要加方括号

d    4
a   -5
c    3
dtype: int64

In [13]:
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
obj2['d']*2

8

In [17]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [20]:
'e' in obj2

False

In [21]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [22]:
obj3 = pd.Series(sdata) #直接通过字典映射，无需额外创建index

In [23]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [24]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [25]:
obj4 = pd.Series(sdata, index =states) #指定index的顺序，原字典中有对应则产生value,没有index中的则不映射

In [26]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
#pandas的isnull和notnull函数可用于检测缺失数据,也可直接用实例判断
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [28]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj4.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [31]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [32]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [33]:
obj3 + obj4  #有点像C++的函数重载加法，两个连接类似数据库的join

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [34]:
obj4.name = 'population'

In [35]:
obj4.index.name = 'state' #增加索引列头

In [36]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [39]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [40]:
obj.index= ['Bob', 'Steve', 'Jeff', 'Ryan']

In [41]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [42]:
obj[['Bob','Ryen','Steve']] #不太推荐此种索引

C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\pandas\core\series.py:1148: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self.loc[key]


Bob      4.0
Ryen     NaN
Steve    7.0
dtype: float64

In [43]:
# DataFrame
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [44]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [45]:
frame.head() #返回前五行的所有数据

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [46]:
pd.DataFrame(data, columns =['year', 'state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [47]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four', 'five', 'six']) #更改了index,增加了一列colums

In [48]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [49]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [50]:
 frame2['state'] #单独取一个column

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [51]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [53]:
#笔记：IPython提供了类似属性的访问（即frame2.year）和tab补全。frame2[column]适用于任何列的名，但是frame2.column只有在列名是一个合理的Python变量名时才适用。

In [54]:
frame2.loc['three'] #获取index为three对应的数据

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
frame2['debt'] = 1.5 #对列增加

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   1.5
two    2001    Ohio  1.7   1.5
three  2002    Ohio  3.6   1.5
four   2001  Nevada  2.4   1.5
five   2002  Nevada  2.9   1.5
six    2003  Nevada  3.2   1.5

In [58]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [59]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [61]:
frame2['debt'] = val    #新列表赋值给frame2的列，会自动匹配index，无法匹配为Nan

In [62]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [63]:
frame2['eastern'] = frame2.state == 'Ohio'

In [64]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [65]:
del frame2['eastern'] #不是副本，会对原DataFrame产生影响  drop函数也可删除

In [66]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [67]:
frame2['eastern'] = frame2.state == 'Ohio'

In [68]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [74]:
frame2.drop(['eastern'],axis =1)

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [75]:
# 嵌套字典
pop = {'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [76]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [77]:
frame3 = pd.DataFrame(pop) #外层字典的键作为列，即Nevada，Ohio，内层键则作为行索引即2000,2001,2002，顺序按起始的

In [78]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [79]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [80]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [81]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}

In [82]:
pdata

{'Ohio': 2001    1.7
 2002    3.6
 Name: Ohio, dtype: float64, 'Nevada': 2001    2.4
 2002    2.9
 Name: Nevada, dtype: float64}

In [83]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [84]:
frame3.index.name = 'year'; frame3.columns.name = 'state' #行表头，列表头

In [85]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [86]:
frame3.values #返回DataFrame的数据

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [87]:
frame2.values

array([[2000, 'Ohio', 1.5, nan, True],
       [2001, 'Ohio', 1.7, -1.2, True],
       [2002, 'Ohio', 3.6, nan, True],
       [2001, 'Nevada', 2.4, -1.5, False],
       [2002, 'Nevada', 2.9, -1.7, False],
       [2003, 'Nevada', 3.2, nan, False]], dtype=object)

In [88]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [89]:
obj

a    0
b    1
c    2
dtype: int64

In [90]:
index = obj.index

In [91]:
index

Index(['a', 'b', 'c'], dtype='object')

In [92]:
index[1:]

Index(['b', 'c'], dtype='object')

In [94]:
#index[1] = 'd'  Index does not support mutable operations

In [98]:
labels = pd.Index(np.arange(3))

In [99]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [100]:
obj2 = pd.Series([1.5, -2.5, 0], index=labels)

In [101]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [102]:
obj2.index is labels

True

In [103]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [104]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [105]:
2003 in frame3.index

False

In [106]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [107]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [108]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [109]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [110]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) #reindex重排索引

In [111]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [112]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [113]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [114]:
 obj3.reindex(range(6), method='ffill')  #关于自动填充的例子

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [115]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'], columns=['Ohio', 'Texas', 'California'])

In [116]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [118]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [119]:
frame2     #重排后数据类型？

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [124]:
frame2.dtypes

Ohio          float64
Texas         float64
California    float64
dtype: object

In [126]:
frame.dtypes

Ohio          int32
Texas         int32
California    int32
dtype: object

In [127]:
states = ['Texas', 'Utah', 'California']

In [128]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [129]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [130]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [131]:
new_obj = obj.drop('c')

In [132]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [133]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [134]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [138]:
s= data.drop(['Colorado', 'Ohio']) #默认从行标签开始删除，axis = 0
s

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [139]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [140]:
data.drop(['two', 'four'], axis=1) #或data.drop(['two','four'],axis ='colums')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [142]:
data.drop(['two','four'],axis ='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [143]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [144]:
obj.drop('c', inplace=True) #inpalce用法

In [145]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [160]:
obj = pd.Series([1,4, 6, 5], index=['a', 'b', 'c', 'd'])

In [161]:
obj

a    1
b    4
c    6
d    5
dtype: int64

In [162]:
obj[[1, 3]]  #index = 1， 3的值

b    4
d    5
dtype: int64

In [163]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [164]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [165]:
 obj['b':'c'] #利用标签的切片运算与普通的Python切片运算不同，其末端是包含的

b    1.0
c    2.0
dtype: float64

In [166]:
 obj['b':'c'] = 5

In [167]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [168]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=['Ohio', 'Colorado', 'Utah', 'New York'], columns=['one', 'two', 'three', 'four'])

In [169]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [170]:
data[:2]  #直接切片是选择index

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [171]:
data['Ohio':'Colorado']

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [172]:
data[data['three'] > 5] #列标签中three大于5

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [174]:
data[data < 5] = 0

In [175]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [176]:
#loc 轴标签 和iloc 整数索引，传入的是整数
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [177]:
data.iloc[2, [3, 0, 1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [178]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [179]:
data.loc[:,'two']

Ohio         0
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [181]:
data.iloc[:, :3] #选择所有index,column选择0:3

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [182]:
data.iloc[:, :3][data.three > 5] #满足[data.three >5]的数据

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [184]:
ser = pd.Series(np.arange(3.))

In [185]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [191]:
#ser[-1] 整数index，不能直接取数

In [189]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [190]:
ser2[-1]

2.0

In [225]:
ser2[:] #ser2[:'c'] #也可直接索银刀标签值, 凡带标签都包含，否则不包含

a    0.0
b    1.0
c    2.0
dtype: float64

In [215]:
ser2.loc['b':'c']  #标签索引，索引到c标签包含, 仅做标签索引，不可用于整数索引，除非index为整数

b    1.0
c    2.0
dtype: float64

In [216]:
ser2.iloc[2:5]  #整数索引，既可用于整数index,也可用于非整数index，cannot do slice indexing

c    2.0
dtype: float64

In [226]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [227]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [228]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [229]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [230]:
s2 + s1

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [231]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [232]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [233]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [234]:
df1+df2  #没有对应的为NaN, 有对应的则相加

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [235]:
df1 = pd.DataFrame({'A': [1, 2]})

In [236]:
df2 = pd.DataFrame({'B': [3, 4]})

In [237]:
df1

A
0  1
1  2

In [238]:
df2

B
0  3
1  4

In [239]:
df1 -df2

A   B
0 NaN NaN
1 NaN NaN

In [240]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),columns=list('abcde'))

In [241]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [242]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [243]:
df2.loc[1, 'b'] = np.nan #标签取数

In [244]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [245]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [246]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [247]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [248]:
1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [249]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [250]:
df1.reindex(columns=df2.columns, fill_value=0) #只对column重排

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [251]:
arr = np.arange(12.).reshape((3, 4))

In [252]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [253]:
arr[0]

array([0., 1., 2., 3.])

In [254]:
arr - arr[0]     #broadcasting，每行都会减去arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [255]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [256]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [260]:
series = frame.iloc[3]

In [261]:
series

b     9.0
d    10.0
e    11.0
Name: Oregon, dtype: float64

In [262]:
frame - series

b    d    e
Utah   -9.0 -9.0 -9.0
Ohio   -6.0 -6.0 -6.0
Texas  -3.0 -3.0 -3.0
Oregon  0.0  0.0  0.0

In [263]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [264]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [265]:
series3 = frame['d']

In [266]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [268]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [281]:
frame.sub(series3, axis=0)

b          d         e
Utah    -1.493384  -1.915527 -0.897171
Ohio    -3.834431  -2.981359 -2.983393
Texas   -6.737989  -7.945230 -8.491699
Oregon -10.257626 -11.912203 -8.958312

In [283]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [284]:
frame

b         d         e
Utah    0.070694  0.356946  1.697024
Ohio   -0.643827 -1.080921 -1.047084
Texas  -0.022370 -1.105227 -0.623382
Oregon  0.736397 -0.267952  1.033824

In [285]:
np.abs(frame)

b         d         e
Utah    0.070694  0.356946  1.697024
Ohio    0.643827  1.080921  1.047084
Texas   0.022370  1.105227  0.623382
Oregon  0.736397  0.267952  1.033824

In [286]:
f = lambda x: x.max() - x.min()

In [287]:
frame.apply(f, axis =1) #对行进行处理，返回index标签， 默认axis = 0对列数据处理

Utah      1.626330
Ohio      0.437094
Texas     1.082857
Oregon    1.301776
dtype: float64

In [288]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min -0.643827 -1.105227 -1.047084
max  0.736397  0.356946  1.697024

In [289]:
format = lambda x: '%.2f' % x

frame.applymap(format) #是因为Series有一个用于应用元素级函数的map方法

b      d      e
Utah     0.07   0.36   1.70
Ohio    -0.64  -1.08  -1.05
Texas   -0.02  -1.11  -0.62
Oregon   0.74  -0.27   1.03

In [290]:
frame['e'].map(format)

Utah       1.70
Ohio      -1.05
Texas     -0.62
Oregon     1.03
Name: e, dtype: object

In [293]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [294]:
obj

d    0
a    1
b    2
c    3
dtype: int64

In [295]:
obj.sort_index() #对index排序

a    1
b    2
c    3
d    0
dtype: int64

In [296]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])

In [297]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [298]:
frame.sort_index(axis=1) #对列column排序

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [299]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [300]:
obj = pd.Series([4, 7, -3, 2])

In [301]:
obj

0    4
1    7
2   -3
3    2
dtype: int64

In [302]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [303]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [304]:
obj

0    4.0
1    NaN
2    7.0
3    NaN
4   -3.0
5    2.0
dtype: float64

In [305]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [306]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})

In [307]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [308]:
frame.sort_values(by='b') #按b列升序

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [309]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [310]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [311]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [312]:
obj.rank()  #rank函数没懂

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [313]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [314]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [317]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})

In [318]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [319]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

In [320]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [321]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [322]:
obj.index.is_unique

False

In [323]:
obj['a']

a    0
a    1
dtype: int64

In [324]:
obj['c']

4

In [325]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [326]:
df

0         1         2
a  0.874466  1.139337 -0.683604
a -0.014035  0.964969 -0.309780
b -1.521701 -0.454469 -0.205263
b -1.097889 -0.418659 -1.057852

In [328]:
df.loc[:'b']

0         1         2
a  0.874466  1.139337 -0.683604
a -0.014035  0.964969 -0.309780
b -1.521701 -0.454469 -0.205263
b -1.097889 -0.418659 -1.057852

In [329]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],[np.nan, np.nan], [0.75, -1.3]],index=['a', 'b', 'c', 'd'], columns=['one', 'two'])

In [330]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [331]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [332]:
df.sum(axis=1)   #跨列

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [333]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [334]:
df.idxmax()

one    b
two    d
dtype: object

In [335]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [336]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [337]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [338]:
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [339]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [340]:
conda install pandas-datareader

SyntaxError: invalid syntax (<ipython-input-340-990bbb6ee910>, line 1)

In [341]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [342]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [343]:
uniques = obj.unique()

In [344]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [348]:
obj.value_counts(0)

c    3
a    3
b    2
d    1
dtype: int64

In [351]:
 pd.value_counts(obj.values, sort=False)

d    1
b    2
a    3
c    3
dtype: int64

In [352]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [353]:
mask = obj.isin(['b', 'c'])

In [354]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [355]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [356]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])

In [357]:
 unique_vals = pd.Series(['c', 'b', 'a'])

In [361]:
s= pd.Index(unique_vals).get_indexer(to_match)

In [359]:
to_match

0    c
1    a
2    b
3    b
4    c
5    a
dtype: object

In [360]:
unique_vals

0    c
1    b
2    a
dtype: object

In [362]:
s

array([0, 2, 1, 1, 0, 2], dtype=int32)

In [363]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3], 'Qu3': [1, 5, 2, 4, 4]})

In [364]:
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [365]:
result = data.apply(pd.value_counts).fillna(0)

In [366]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0